#!/bin/sh
if [ $# -ne 1 ]; then
   echo "  Usage: buildman commandname"
   echo "  The result is in file r1.html"
   exit 1
fi
# <!ENTITY quot CDATA  "&#22;">
cat -  > temp$$ <<wrapper
<!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook XML V4.1.2//EN" "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" [
  <!ENTITY refentrypage SYSTEM "$1.refentry">
 ]>
<article>
&refentrypage;
</article>
wrapper
UNAME_S=$(uname -s)
if [ "$UNAME_S" = "Darwin" ]; then
    pandoc -f docbook -t man -o $1.1 temp$$
else
    xmlto man temp$$
fi
rm temp$$
